services:
  backend:
    container_name: backend
    env_file:
      - ${ENV_FILE:-.env.docker}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:${BACKEND_PORT}"
    networks:
      - custom
    depends_on:
      postgres:
        condition: service_healthy
    command: "gunicorn -c conf/gunicorn.conf.py 'auth.run:make_app()'"

  postgres:
    container_name: postgres
    image: postgres:13.0-alpine
    env_file:
      - ${ENV_FILE:-.env.docker}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - custom
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:${POSTGRES_PORT}"

networks:
  custom:
    driver: bridge