from enum import StrEnum


class JobStatus(StrEnum):
    NEW = "NEW"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TransportType(StrEnum):
    CAR = "CAR"
    NONE = "NONE"


class PlanningRunStatus(StrEnum):
    CREATED = "CREATED"
    PREPARING = "PREPARING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    FAILED_VALIDATION = "FAILED_VALIDATION"


class ReasonCode(StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_SERVICE_DURATION = "MISSING_SERVICE_DURATION"
    INVALID_TIME_WINDOW = "INVALID_TIME_WINDOW"
    GEOCODING_FAILED = "GEOCODING_FAILED"
    TRAVEL_DATA_NOT_READY = "TRAVEL_DATA_NOT_READY"
    NO_AVAILABLE_ENGINEER = "NO_AVAILABLE_ENGINEER"
    NO_COMPATIBLE_ENGINEER = "NO_COMPATIBLE_ENGINEER"
    DATASET_LIMIT = "DATASET_LIMIT"
    NOT_SELECTED_BY_OPTIMIZER = "NOT_SELECTED_BY_OPTIMIZER"


ACTIVE_RUN_STATUSES = (
    PlanningRunStatus.CREATED.value,
    PlanningRunStatus.PREPARING.value,
    PlanningRunStatus.RUNNING.value,
)
