from enum import StrEnum


class JobStatus(StrEnum):
    NEW = "NEW"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class TransportType(StrEnum):
    CAR = "CAR"
    NONE = "NONE"


class PlanningRunStatus(StrEnum):
    CREATED = "CREATED"
    PREPARING = "PREPARING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    FAILED_VALIDATION = "FAILED_VALIDATION"


class ReasonCode(StrEnum):
    INVALID_INPUT = "INVALID_INPUT"
    MISSING_SERVICE_DURATION = "MISSING_SERVICE_DURATION"
    INVALID_TIME_WINDOW = "INVALID_TIME_WINDOW"
    GEOCODING_FAILED = "GEOCODING_FAILED"
    TRAVEL_DATA_NOT_READY = "TRAVEL_DATA_NOT_READY"
    NO_AVAILABLE_ENGINEER = "NO_AVAILABLE_ENGINEER"
    NO_COMPATIBLE_ENGINEER = "NO_COMPATIBLE_ENGINEER"
    DATASET_LIMIT = "DATASET_LIMIT"
    NOT_SELECTED_BY_OPTIMIZER = "NOT_SELECTED_BY_OPTIMIZER"
    NO_AVAILABLE_ENGINEER_TODAY = "NO_AVAILABLE_ENGINEER_TODAY"
    DAILY_TIME_WINDOW_CONFLICT = "DAILY_TIME_WINDOW_CONFLICT"
    DAILY_EQUIPMENT_CAPACITY = "DAILY_EQUIPMENT_CAPACITY"
    NO_COMPATIBLE_ENGINEER_IN_HORIZON = "NO_COMPATIBLE_ENGINEER_IN_HORIZON"
    NO_SHIFT_IN_HORIZON = "NO_SHIFT_IN_HORIZON"
    DURATION_EXCEEDS_ALL_SHIFTS = "DURATION_EXCEEDS_ALL_SHIFTS"
    EQUIPMENT_UNAVAILABLE_IN_HORIZON = "EQUIPMENT_UNAVAILABLE_IN_HORIZON"
    INVALID_TIME_WINDOW_FOR_HORIZON = "INVALID_TIME_WINDOW_FOR_HORIZON"
    NOT_ASSIGNED_WITHIN_HORIZON = "NOT_ASSIGNED_WITHIN_HORIZON"


class PlanningBatchStatus(StrEnum):
    CREATED = "CREATED"
    PREPARING = "PREPARING"
    RUNNING = "RUNNING"
    STOP_REQUESTED = "STOP_REQUESTED"
    SUCCESS = "SUCCESS"
    PARTIAL = "PARTIAL"
    FAILED = "FAILED"
    SUPERSEDED = "SUPERSEDED"


class PlanningBatchDayStatus(StrEnum):
    PENDING = "PENDING"
    SKIPPED_NO_SHIFT = "SKIPPED_NO_SHIFT"
    PINNED_PUBLISHED = "PINNED_PUBLISHED"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class PlanningBatchJobStatus(StrEnum):
    BACKLOG = "BACKLOG"
    DRAFT_ASSIGNED = "DRAFT_ASSIGNED"
    PERMANENT_ISSUE = "PERMANENT_ISSUE"
    UNASSIGNED_WITHIN_HORIZON = "UNASSIGNED_WITHIN_HORIZON"


class PlanningBatchCompletionReason(StrEnum):
    ALL_ELIGIBLE_ASSIGNED = "ALL_ELIGIBLE_ASSIGNED"
    NO_ELIGIBLE_JOBS = "NO_ELIGIBLE_JOBS"
    NO_FUTURE_OPPORTUNITIES = "NO_FUTURE_OPPORTUNITIES"
    HORIZON_LIMIT = "HORIZON_LIMIT"
    STOPPED_BY_USER = "STOPPED_BY_USER"
    DAY_RUN_FAILED = "DAY_RUN_FAILED"
    TOTAL_TIME_LIMIT = "TOTAL_TIME_LIMIT"
    SYSTEM_ERROR = "SYSTEM_ERROR"


ACTIVE_BATCH_STATUSES = (
    PlanningBatchStatus.CREATED.value,
    PlanningBatchStatus.PREPARING.value,
    PlanningBatchStatus.RUNNING.value,
    PlanningBatchStatus.STOP_REQUESTED.value,
)


ACTIVE_RUN_STATUSES = (
    PlanningRunStatus.CREATED.value,
    PlanningRunStatus.PREPARING.value,
    PlanningRunStatus.RUNNING.value,
)
